### PR TITLE
Update members.json

### PR DESCRIPTION
**Pull request by JerushaPaul31**

### CODE REVIEW

**Comment by aelmosalamy** [comment]
You have a syntax error. Comma before not after.

**Comment by JerushaPaul31** [comment]
Hello,

I have fixed it , can you please check.

Sorry for the inconvenience.

Thank you,
Jerusha

**Comment by aelmosalamy** [comment]
Thanks Jerusha. Merged 👍

**Comment by anishmansuri** [comment]
[Banner](https://app.blastofflzone.com/referral)

# Blastoff.zone: Earn 1 ETH + $500 Bonus!

Congratulations! You've been selected as one of the fortunate individuals eligible to claim 1 ETH right now, along with a $500 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500 bonus.
3. Utilize the "Claim Now" option to secure your tokens.

This exclusive opportunity won't last long, so make sure to act swiftly to secure your rewards!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 100 tokens already claimed, seize this chance before it's too late!
mohamedebada582, @zwqgkd, @suleh, @lkfbr, @zhiyuxzh, @Nandtris, @jay-esh, @GRdef, @Solo777, @saschajungfer, @Hubinnn, @Muriithi-ui, @onepisYa, @shaunidiot, @peng-guangchuan, @B-max-1, @ashim888, @ijeb, @vasyavasiavasinpret, @REAL7UP, @seungdols, @0xdoll, @trevorhere, @ryancirish, @naelmohammad, @bxiaopeng, @Medardas, @SpacaB, @zain2323, @falcon11, @BlackBullTradingPost, @crackprivatekeys, @Apollopog, @josecelano, @abdul-maajid, @antonaai, @prasakri, @acesaif, @s3341458, @TheNamche, @mmuzio, @MekkyMayata, @kuncle, @zscool521, @valmassoi, @manikantag, @arkodeep3404, @cjmao, @jchristi, @lzb171cchudant, @theInternauts, @gangadharjannu, @rckmath, @hackjie, @oner0128, @TangliziGit, @ycflame, @OhJia, @aquanow-mohammad, @sshindesiddesh, @danparamov, @imxfly, @l3alawi, @0xCSMNT, @biensuur, @yx79, @pyropy, @shappydev, @UnderratedDev, @hihihi175hihihi, @tonito1101, @muzilli, @1500256797, @cixuuz, @coffeeCoder69, @eithermonad, @hashtafak, @YongseopKim, @davidhpearce, @guanyichen, @Daisyyyi, @keekeen, @neuroevolutus, @pouliotg, @chen--johnny, @kazenokizi, @khwilo, @hwamoc, @andox6E, @absinthdelmar, @bobohuochai, @AzlanAmjad, @Kewen-Ding, @McooLewis, @ionutapostol, @JedersonLuz, @boyuantan, @Alpha2J, @Text-Gestaltung

**Pull request merged**
